<div class="hbr-main pad-main">
<div class="block-title-main">
<h2>V4U OwlCarousel Slider</h2>
<div class="title-border"></div>
</div>
<div class="hbr-main">
<div style="margin: 0 -10px;">
<div class="hbr-content hbr-slider">
<div class="hbr-inner">1</div>
<div class="hbr-inner">2</div>
<div class="hbr-inner">3</div>
<div class="hbr-inner">4</div>
<div class="hbr-inner">5</div>
<div class="hbr-inner">6</div>
<div class="hbr-inner">7</div>
</div>
</div>
<script type="text/javascript" xml="space">// <![CDATA[
            require(['jquery', 'cpowlcarousel'], function ($) {
                jQuery(document).ready(function () {
                    jQuery(".hbr-slider").owlCarousel({
                        items: 5,
                        itemsDesktop: [1080, 4],
                        itemsDesktopSmall: [860, 3],
                        itemsTablet: [768, 3],
                        itemsTabletSmall: [639, 3],
                        itemsMobile: [479, 2],
                        pagination: false,
                        navigationText: ['<div class="lft-btn"><i class="fa fa-angle-left"></i></div>', '<div class="rgt-btn"><i class="fa fa-angle-right"></div>'],
                        navigation: true,
                    });
                });
            });
// ]]></script>
</div>
</div>